### ISSUE TITLE
learn html 

### ISSUE THREAD

**Issue by GuyARoss** [wowotek/wowotek#1]
Brrooo your html is broken, plz fix. https://www.w3schools.com/html/

**Comment by kaitoyonde** [comment]
> Brrooo your html is broken, plz fix. https://www.w3schools.com/html/

LoL i just can't find the time to finish this shit.

**Comment by GuyARoss** [comment]
> > Brrooo your html is broken, plz fix. https://www.w3schools.com/html/
> 
> LoL i just can't find the time to finish this shit.

Lool, blizz will put in a PR!

**Comment by kaitoyonde** [comment]
> > > Brrooo your html is broken, plz fix. https://www.w3schools.com/html/
> > 
> > 
> > LoL i just can't find the time to finish this shit.
> 
> Lool, blizz will put in a PR!

I betch'a he wont

**Comment by kaitoyonde** [comment]
@GuyARoss I Fixed it !
